### ISSUE TITLE
remote_path always gets module name appended

### ISSUE THREAD

**Issue by IzzySoft** [SebKuzminsky/rsync-push-backup#10]
I've defined `remote_path=/mnt/data/backup/test` – but backups end up in `/mnt/data/backup/test/test`? Counter-check: They end up in `${remote_path}/${MODULE}`. While that might seem useful if one knows, it might not be what one expects.

If that's intentional, we should document it – otherwise we should fix it. I'm not sure which one would be right, but tend to the latter, as otherwise one is forced to keep the two names in sync. To compromise, we might add a config variable for whether to append the module name to the `remote_path` and have it default to "yes", so one has at least a chance to switch that off?

Priority: Minor, Impact: Low :)

**Comment by SebKuzminsky** [comment]
What's the name of your module, and what's the value of the module's backup_root?

Now that there are multiple modules, each potentially with its own snapshot rotation schedule, the destination directory must be specific to each module.  If multiple modules were backed up to the same directory, they would also share snapshot schedules.

So currently, on the backup server, the ${remote_root} contains a subdirectory for each module, and each module's directory contains all the snapshots for that module.

Make sense?

The new doc/README.md file you added alludes to this at the end:

> ## Results
> 
> The result (on the backup server) will look something like this for each module:

But maybe it could be made more explicit, perhaps by showing a directory tree diagram like it does for the .backup dir (at the top of the README).

**Comment by SebKuzminsky** [comment]
Note that with the current architecture we can't back up multiple modules into the same remote directory.  Currently we run "rsync --delete" once for each module, and if they went into the same dir they would remove each other!

You can imagine changing the backup script to concatenate all the modules' ${backup_root} and just run rsync once, that would get around the problem.  Then we could change the backup script to rsync all the modules, _then_ rotate the snapshots just once.  We'd also have to say that modules do not get to specify snapshot rotation schedules; that those only go in the top-level config (since they'd all rotate together).  I'm not sure how we would handle the per-module exclude files in this alternate scheme...

I have some backups that I want lots of snapshots of (my $HOME) and some that i only want a few, spread out in time (virtual machine disk images), but i could implement that using multiple .backup dirs, and run the backup script multiple times with different -c settings.

I think they're about equivalent in terms of usability.  I'd prefer not to change it, because I'm lazy and because i don't think it would add much (and because i don't know how to deal with per-module excludes).  If i'm missing some advantage of co-mingling the modules please clue me in and i'll reconsider.

My feeling is that the current behavior is correct, and this is a documentation issue.

**Comment by IzzySoft** [comment]
> So currently, on the backup server, the ${remote_root} contains a subdirectory for each module, and each module's directory contains all the snapshots for that module.

Yes, understood that. Need some getting-used-to, though – as one doesn't expect something gets appended to the configured path (especially when neither comments nor documentation point that out). And I fully understand that, if the module doesn't define its own target, some differentiation must be made.

Idea: as the global config is sourced first anyway, make a copy of the target path (e.g. `global_remote_path`). Then, after sourcing the module's config, check `[[ "${remote_path}" == "${global_remote_path}" ]]` – and if that returns `true`, append the module name, but otherwise leave it alone?

Reflecting your edit done while I was writing this: your "lazyness" wouldn't be affected if we do it that way :)

PS: My approach would still not cover two _modules_ defining the same target (which would cause the trouble you're pointing out). And as the user might always run each module separately, we couldn't even "remember" that from each module run. So it indeed might be _safest_ (not sure about best, but at least fool-proof) to have it the way it is. The minimal restriction it puts on "pwer-users who know what they're doing" must be lived with then. If you share that concern, we should leave it this way and just point it out in the documentation.

Whatever path we chose, the documentation definitely needs to be updated to reflect the behaviour (speaking of which: for the TOC, shall we use Github-flavored MD to link to the anchors auto-created at Github?).

**Comment by IzzySoft** [comment]
Yupp, fits. Could have ended with "… using the modules name" – but hey, they will find out :) Thanks!

**Comment by SebKuzminsky** [comment]
Feel free to add it if you want.

**Comment by IzzySoft** [comment]
Done. PR on the way :)
